# Copyright 2026 OpenSynergy Indonesia
# Copyright 2026 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Partner",
    "version": "19.0.1.4.0",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "contributors": [
        "Andhitia Rama <andhitia.r@gmail.com>",
    ],
    "license": "AGPL-3",
    "installable": True,
    "application": True,
    "depends": [
        "contacts",
        "ssi_master_data_mixin",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/res_groups/company_ownership_type.xml",
        "security/res_groups/company_entity_type.xml",
        "security/res_groups/res_partner_religion.xml",
        "security/res_groups/res_partner_ethnicity.xml",
        "security/res_groups/res_partner_bank_usage.xml",
        "security/res_groups/res_partner_title.xml",
        "security/res_groups/partner_contact_group.xml",
        "security/res_groups/res_partner_id_category.xml",
        "security/res_groups/partner_field_of_study.xml",
        "security/res_groups/partner_formal_education_level.xml",
        "security/ir_model_access/company_ownership_type.xml",
        "security/ir_model_access/company_entity_type.xml",
        "security/ir_model_access/res_partner_religion.xml",
        "security/ir_model_access/res_partner_ethnicity.xml",
        "security/ir_model_access/res_partner_bank_usage.xml",
        "security/ir_model_access/res_partner_title.xml",
        "security/ir_model_access/partner_contact_group.xml",
        "security/ir_model_access/res_partner_id_category.xml",
        "security/ir_model_access/res_partner_id_number.xml",
        "security/ir_model_access/partner_language.xml",
        "security/ir_model_access/partner_field_of_study.xml",
        "security/ir_model_access/partner_formal_education_level.xml",
        "security/ir_model_access/partner_academic.xml",
        "security/ir_model_access/partner_certification.xml",
        "security/ir_model_access/partner_experience.xml",
        "menu.xml",
        "views/mixin_partner_experience.xml",
        "views/res_partner.xml",
        "views/company_ownership_type.xml",
        "views/company_entity_type.xml",
        "views/res_partner_religion.xml",
        "views/res_partner_ethnicity.xml",
        "views/res_partner_bank_usage.xml",
        "views/res_partner_title.xml",
        "views/res_partner_bank.xml",
        "views/partner_contact_group.xml",
        "views/res_partner_id_category.xml",
        "views/partner_field_of_study.xml",
        "views/partner_formal_education_level.xml",
        "views/partner_academic.xml",
        "views/partner_certification.xml",
        "views/partner_experience.xml",
    ],
}
